export { default as Lottery } from './Lottery.vue'
export { default as Goodies } from './Goodies.vue'
export { default as Activity } from './Activity.vue'
export { default as Match } from './Match.vue'
export { default as Tab } from './Tab.vue'
export { default as CHeader } from './CHeader.vue'
